import {seniorUIUXDesigner} from '../../assets/index'

export const companyData = [
  {
    image: seniorUIUXDesigner,
    name: 'Rockstar Games New York',
    position: 'Online English Teachers',
    location: 'Las Vegas, USA',
    date: '2 Days ago',
    fullTime: true,
    partTime: false,
    contract: false,
    remote: true,
    onsite: false,
    minPrice: '$23,000',
    maxPrice: '$25,000',
    per: 'Month',
    description: 'This role involves teaching English to online students. You will create and deliver engaging and interactive lessons to help students improve their English language skills.',
    requirements: '1. Bachelor\'s degree in English or related field\n2. TEFL or TESOL certification\n3. Strong communication skills',
    responsibilities: '1. Conduct online English classes\n2. Prepare and deliver lessons\n3. Assess student progress and provide feedback',
  },
  {
    image: 'image',
    name: 'Rockstar Games New York',
    position: 'Database Administrator',
    location: 'Las Vegas, USA',
    date: '2 Days ago',
    fullTime: true,
    partTime: false,
    contract: false,
    remote: true,
    onsite: false,
    minPrice: '$23,000',
    maxPrice: '$25,000',
    per: 'Month',
    description: 'As a Database Administrator, you will be responsible for managing and maintaining the company\'s databases, ensuring data security, and optimizing database performance.',
    requirements: '1. Bachelor\'s degree in computer science or a related field\n2. Proven experience in database management\n3. Knowledge of SQL and database optimization',
    responsibilities: '1. Install and configure database systems\n2. Monitor database performance\n3. Ensure data security and integrity',
  },
  {
    image: 'image',
    name: 'Rockstar Games New York',
    position: 'IT Project Manager',
    location: 'Las Vegas, USA',
    date: '2 Days ago',
    fullTime: true,
    partTime: false,
    contract: false,
    remote: true,
    onsite: false,
    minPrice: '$23,000',
    maxPrice: '$25,000',
    per: 'Month',
    description: 'The IT Project Manager will lead and oversee IT projects, ensuring they are completed on time and within budget. This role involves managing project teams and resources.',
    requirements: '1. Bachelor\'s degree in IT or a related field\n2. Proven experience in IT project management\n3. Strong leadership and communication skills',
    responsibilities: '1. Plan and execute IT projects\n2. Manage project teams and resources\n3. Monitor project progress and report to stakeholders',
  },
  {
    image: 'image',
    name: 'Rockstar Games New York',
    position: 'Junior UI/UX Designer',
    location: 'Las Vegas, USA',
    date: '2 Days ago',
    fullTime: true,
    partTime: false,
    contract: false,
    remote: true,
    onsite: false,
    minPrice: '$23,000',
    maxPrice: '$25,000',
    per: 'Month',
    description: 'The Junior UI/UX Designer will work on creating user-friendly and visually appealing interfaces. You will collaborate with the design team to create wireframes and prototypes.',
    requirements: '1. Bachelor\'s degree in design or a related field\n2. Proficiency in design software\n3. Strong design and problem-solving skills',
    responsibilities: '1. Collaborate with the design team\n2. Create wireframes and prototypes\n3. Conduct user research and testing',
  },
  {
    image: 'image',
    name: 'Rockstar Games New York',
    position: 'AI/Machine Learning Engineer',
    location: 'Las Vegas, USA',
    date: '2 Days ago',
    fullTime: true,
    partTime: false,
    contract: false,
    remote: true,
    onsite: false,
    minPrice: '$23,000',
    maxPrice: '$25,000',
    per: 'Month',
    description: 'The AI/Machine Learning Engineer will work on developing and implementing machine learning algorithms and models. You will collaborate with the data science team to analyze and interpret data.',
    requirements: '1. Master\'s degree in AI, machine learning, or a related field\n2. Proficiency in machine learning frameworks\n3. Strong analytical and problem-solving skills',
    responsibilities: '1. Develop machine learning models\n2. Collaborate with the data science team\n3. Analyze and interpret data for insights',
  },
  {
    image: 'image',
    name: 'Rockstar Games New York',
    position: 'SEO Analyst & Reviewer',
    location: 'Las Vegas, USA',
    date: '2 Days ago',
    fullTime: true,
    partTime: false,
    contract: false,
    remote: true,
    onsite: false,
    minPrice: '$23,000',
    maxPrice: '$25,000',
    per: 'Month',
    description: 'As an SEO Analyst & Reviewer, you will be responsible for optimizing website content and analyzing SEO performance. You will conduct reviews to improve search engine rankings.',
    requirements: '1. Bachelor\'s degree in marketing or a related field\n2. Proven experience in SEO\n3. Strong analytical skills',
    responsibilities: '1. Optimize website content for SEO\n2. Analyze SEO performance\n3. Conduct reviews to improve search engine rankings',
  },
  {
    image: 'image',
    name: 'Rockstar Games New York',
    position: 'Content Writer and Speaker',
    location: 'Las Vegas, USA',
    date: '2 Days ago',
    fullTime: true,
    partTime: false,
    contract: false,
    remote: true,
    onsite: false,
    minPrice: '$23,000',
    maxPrice: '$25,000',
    per: 'Month',
    description: 'The Content Writer and Speaker will create engaging content for the company\'s audience. You will also participate in speaking engagements and presentations.',
    requirements: '1. Bachelor\'s degree in journalism, communications, or a related field\n2. Strong writing and speaking skills\n3. Creative and engaging content creation',
    responsibilities: '1. Create engaging content for various platforms\n2. Participate in speaking engagements and presentations\n3. Engage with the audience and build relationships',
  },
  {
    image: 'image',
    name: 'Rockstar Games New York',
    position: 'Social Media Expert',
    location: 'Las Vegas, USA',
    date: '2 Days ago',
    fullTime: true,
    partTime: false,
    contract: false,
    remote: true,
    onsite: false,
    minPrice: '$23,000',
    maxPrice: '$25,000',
    per: 'Month',
    description: 'The Social Media Expert will manage and optimize the company\'s social media presence. You will develop and implement social media strategies to engage the audience.',
    requirements: '1. Bachelor\'s degree in marketing or a related field\n2. Proven experience in social media management\n3. Knowledge of social media platforms',
    responsibilities: '1. Manage and optimize social media presence\n2. Develop and implement social media strategies\n3. Engage with the audience and monitor performance',
  },
  {
    image: 'image',
    name: 'Rockstar Games New York',
    position: 'Senior UI/UX Designer',
    location: 'Las Vegas, USA',
    date: '2 Days ago',
    fullTime: true,
    partTime: false,
    contract: false,
    remote: true,
    onsite: false,
    minPrice: '$23,000',
    maxPrice: '$25,000',
    per: 'Month',
    description: 'The Senior UI/UX Designer will lead design projects and mentor junior designers. You will be responsible for creating user-friendly interfaces and improving user experiences.',
    requirements: '1. Bachelor\'s degree in design or a related field\n2. Proven experience in UI/UX design\n3. Leadership and mentoring skills',
    responsibilities: '1. Lead design projects and mentor junior designers\n2. Create user-friendly interfaces\n3. Improve user experiences and design consistency',
  },
];
